# You can disable rules that have been enabled by default
disabled_rules:
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
#  - nesting
#  - operator_whitespace
#  - opening_brace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
 - trailing_whitespace
#  - type_body_length
# - type_name
# - valid_docs
# - variable_name
# - variable_name_min_length
# - variable_name_max_length
# - identifier_name

# You can enable rules that have been disabled by default
opt_in_rules:
  - first_where
  # - function_default_parameter_at_end
  - function_parameter_count
  - function_body_length
  # - implicitly_unwrapped_optional

# Exclude directories that you don't want to lint
excluded:
  - Carthage
  - Pods
  - fastlane
  - XLProjectName/Helpers/R-Swift/R.generated.swift
  - /App789_iOS/CITreeView/

# Use "xcode" so that when you build, the result will be shown in Xcode
reporter: "xcode" # Other reporters: json, csv, checkstyle, junit, html, emoji

# parameterized rules can be customized from this configuration file
file_length:
  - 700
  - 1000
line_length:
  - 230
  - 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 30 # warning
  - 40 # error
variable_name_min_length:
  - 2 # warning
  - 1 # error